nva/nvapy: Fix nvapy python module import
Without this the following error occurs when importing the nvapy module:

>>> import nvapy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: nva/nvapy.so: undefined symbol: gpu_list

Fixes: 9e6b83e5 ("Single Source of Truth.")